#ifndef CASE_H
#define CASE_H

#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>

#include <string>

class Case
{
    public:
        Case();
        Case(sf::RenderWindow* window, float x=0, float y=0);
        virtual ~Case();

        float GetpositionX() { return m_positionX; }
        void SetpositionX(float val) { m_positionX = val; }

        float GetpositionY() { return m_positionY; }
        void SetpositionY(float val) { m_positionY = val; }
        void Setposition(float x, float y){m_positionX=x;m_positionY=y;}

        int Getvalue(){return m_value;}

        sf::RenderWindow* Getwindow() { return m_window; }
        void Setwindow(sf::RenderWindow* val) { m_window = val; }

        sf::Texture Gettexture() { return m_texture; }
        void Settexture(std::string name) ;

        sf::Sprite Getsprite() { return m_sprite; }
        void Setsprite(sf::Sprite val) { m_sprite = val; }
        /// /// /// /// ///
        void draw(int whichOneX,int whichOneY,int x, int y);
        void drawFree(int whichOneX,int whichOneY,float x, float y);
        bool ifClicked();

    protected:
        float m_positionX;
        float m_positionY;
        int m_value;
        bool m_statut;
        sf::RenderWindow* m_window;
        sf::Texture m_texture;
        sf::Sprite m_sprite;
};

#endif // CASE_H
