#ifndef CASE_H
#define CASE_H

#include <SFML/Graphics.hpp>
#include <SFML/System.hpp>
#include <SFML/Window.hpp>

#include <string>

class Case
{
    public:
        Case();
        Case(sf::RenderWindow* window, float x=0, float y=0);
        virtual ~Case();

        sf::RenderWindow* Getwindow() { return m_window; }

        void Settexture(std::string name) ;

        /// /// /// /// ///
        void draw(int whichOneX,int whichOneY,int x, int y);

        bool ifClicked();

    protected:
        float m_positionX;
        float m_positionY;
        int m_value;
        bool m_statut;
        sf::RenderWindow* m_window;
        sf::Texture m_texture;
        sf::Sprite m_sprite;
};

#endif // CASE_H
